# Generated by Django 3.1.5 on 2021-01-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210130_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='owner',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='todo_owner',
        ),
    ]
